image: ubuntu:18.04

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
services:
  - docker:dind

stages:
  - sync
  - build
  - deploy

include:
  - local: 'configs/sync.yaml'
  - local: 'configs/build.yaml'
  - local: 'configs/deploy.yaml'