variables:
  DOCKER_DRIVER: overlay2
  # DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh", "--insecure-registry=repo.dev.hrl.internal:5000"]


stages:
  - sync
  - build
  - deploy

include:
  - local: 'configs/sync.yaml'
  - local: 'configs/build.yaml'
  - local: 'configs/deploy.yaml'