---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: registry.dev.hrl.internal:5000/website
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
