---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
spec:
  selector:
    app: website
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
