---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
      traefik.http.services.stuff.loadbalancer.healthcheck.path: /health
      traefik.http.services.stuff.loadbalancer.healthcheck.interval: 15s
      traefik.http.services.stuff.loadbalancer.healthcheck.timeout: 1s
spec:
  selector:
    app: website
  type: LoadBalancer
  loadBalancerIP: "k3s.dev.hrl.internal"
  ports:
    - name: http
      port: 80
      targetPort: 3000
