---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
spec:
  selector:
    app: website
  type: ClusterIP
  ports:
    - name: http
      port: 80
  clusterIP: k3s.dev.hrl.internal