---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
spec:
  selector:
    app: website
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  livenessProbe:
    httpGet:
      scheme: HTTP
      path: /
      port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
  readinessProbe:
    httpGet:
      scheme: HTTP
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
