---
apiVersion: v1 
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app-nodeport
    app.kubernetes.io/version: 0.0.1
  name: app-nodeport
  namespace: app
spec:
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      nodePort: 30986
  selector:
    app: app
  type: NodePort