---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
  annotations:
    kubernetes.io/hostname: "k3s.dev.hrl.internal"
spec:
  selector:
    app: website
  type: LoadBalancer
  loadBalancerIP: "k3s.dev.hrl.internal"
  ports:
    - name: http
      port: 80
      targetPort: 3000
  livenessProbe:
    httpGet:
      scheme: HTTP
      path: /health
      port: 80
      initialDelaySeconds: 10
      periodSeconds: 45
  readinessProbe:
    httpGet:
      scheme: HTTP
      path: /health
      port: 80
      initialDelaySeconds: 10
      periodSeconds: 45
