build:
  image: docker:latest
  tags: [ local-gitlab-dev ]
  stage: build
  rules:
    - if: '$TARGETTASKNAME!= "sync-task"'
  script:
    - apk update
    - apk add curl
    - apk add jq
    - |
      export VERSION=$(\
        curl -X GET http://registry.dev.hrl.internal:5000/v2/website/tags/list \
          | jq -r '.tags[] | sub("^v.*";"")' | sort -Vr \
          | awk -F. '{$1++;print}' \
        )
    - docker build -t api-website ./website
    - docker tag api-website registry.dev.hrl.internal:5000/website:$VERSION
    - docker push registry.dev.hrl.internal:5000/website:$VERSION
