build:
  image: docker:latest
  before_scripts:
    - mkdir -p /etc/docker
    - |
      cat > /etc/docker/daemon.json <<EOF
      {
        "insecure-registries" : [ "registry.dev.hrl.internal:5000" ]
      }
      EOF
    - systemctl restart docker
  tags: [ local-gitlab-dev ]
  stage: build
  rules:
    - if: '$TARGETTASKNAME!= "sync-task"'
  script:
    - docker build -t api-website ./website
    - docker tag api-website registry.dev.hrl.internal:5000/website:0.0.1
    - docker push registry.dev.hrl.internal:5000/website:0.0.1
