deploy:
  image: ubuntu:18.04
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  tags: [ local-gitlab-dev ]
  stage: deploy
  needs: [ 'build' ]
  rules:
    - if: '$TARGETTASKNAME!= "sync-task"'
  script:
    - apt-get update
    - |
      apt-get install -y \
        curl \
        jq \
        git \
        wget
    - wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    - chmod a+x /usr/local/bin/yq
    - |
      export VERSION=$(\
        curl -X GET http://registry.dev.hrl.internal:5000/v2/website/tags/list \
          | jq -r '.tags[] | sub("^v.*";"")' | sort -Vr
        )
    - yq -i ".spec.template.spec.containers[0].image = \"registry.dev.hrl.internal:5000/website:$VERSION\"" manifests/deployment.yaml
    - cat manifests/deployment.yaml
    - git config --global user.email "srv@hrl.internal"
    - git config --global user.name "Service Account"
    - git checkout master
    - git branch --all
    - git add -A
    - git commit -m "Bump Version - Automatic - [ci skip]"
    - git remote set-url origin git@repo.dev.hrl.internal:root/website.git
    - git -c core.sshCommand='ssh -o StrictHostKeyChecking=accept-new' push -u origin master
